# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc188339a640d42507393dde01fd57e93ae0f4224ad8e341cfe8b8e31939b38f809a22bcb72d4e0697986d06f4f26daee3f968ff015e46bab4c92b356287233

test:
  secret_key_base: d76eb64a45e0a23962fdc8a58e0e0bf590a56fb8fa05a9f99f7561f3e04bbf2233c04d3ff8c243e2282f0a86cbfc8bab619047a24fb5e12a2a201bddba5c6706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
